language: scala
scala:
  - 2.12.1
script:
  - sbt clean && sbt compile && sbt test coverageReport
after_success:
  - sbt coverageReport coveralls
notifications:
  email:
    on_success: never
    on_failure: never